// pest. The Elegant Parser
// Copyright (C) 2017  Dragoș Tiselice
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

string = { "abc" }
insensitive = { ^"abc" }
range = { '0'..'9' }
ident = { string }
pos_pred = { &string }
neg_pred = { !string }
double_neg_pred = { !!string }
sequence = !{ string ~ string }
sequence_atomic = @{ string ~ string }
sequence_non_atomic = @{ sequence }
choice = { string | range }
optional = { string? }
repeat = { string* }
repeat_atomic = @{ string* }
repeat_once = { string+ }
repeat_once_atomic = @{ string+ }
peek_ = { push(range) ~ push(range) ~ peek ~ peek }
pop_ = { push(range) ~ push(range) ~ pop ~ pop }
pop_fail = { push(range) ~ !pop ~ range ~ pop }
whitespace = _{ " " }
