program = _{ SOI ~ implicit ~ EOI  }
implicit= ${ #head = or ~ #tail = (WHITESPACE+ ~ or)* }

or  = !{ and ~ (or_op ~ and)+ #more_and | and #one_and }
and = { comp ~ (and_op ~ comp)+ #more_comp | comp #one_comp }
comp = { array ~ eq_op ~ array #more_array | array #one_array }

array = ${ term }

term = _{ ASCII_ALPHANUMERIC+ }
or_op = { "||" }
and_op = { "&&" }
eq_op = { "=" }
WHITESPACE = _{ " " | "\t" | NEWLINE }