/// An `enum` representing tokens generated by a parser.
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum Token<Rule> {
    /// The starting bit of the `Token`.
    TokenStart(Rule, usize),
    /// The ending bit of the `Token`.
    TokenEnd(Rule, usize)
}
